apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  namespace: monitoring
  labels:
    monitoring: "true"
spec:
  namespaceSelector:
    matchNames:
      - bi-infra
  selector:
    matchLabels:
      app: postgres-exporter
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
