apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: airflow-statsd
  namespace: monitoring
  labels:
    monitoring: "true"
spec:
  namespaceSelector:
    matchNames:
      - bi-orchestration
  selector:
    matchLabels:
      app: statsd-exporter
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
