apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
  - name: web
    port: 16686
    targetPort: 16686
    nodePort: 30686
