apiVersion: v1
kind: ConfigMap
metadata:
  name: wso2apim-config
  namespace: apim-wso2
data:
  # TODO: ajustar deployment.toml.tpl segun tu entorno (DB externa, hostname, etc.)
  deployment.toml.tpl: |
    [server]
    hostname = "apim-wso2.local"
    node_ip = "$env{NODE_IP}"

    [transport.https]
    port = 9443

    [apim.gateway.environment]
    name = "Default"
    type = "production"
    display_in_api_console = true
    description = "This is a hybrid gateway that handles both production and sandbox token traffic."

    [[apim.gateway.environment]]
    name = "Default"
    type = "production"

    [apim.key_manager]
    service_url = "https://localhost:${mgt.transport.https.port}/services/"

    [database.shared_db]
    type = "postgre"
    url = "jdbc:postgresql://wso2-postgres.apim-wso2.svc.cluster.local:5432/wso2_shared_db"
    username = "wso2"
    password = "__DB_PASSWORD__"

    [database.apim_db]
    type = "postgre"
    url = "jdbc:postgresql://wso2-postgres.apim-wso2.svc.cluster.local:5432/wso2_apim_db"
    username = "wso2"
    password = "__DB_PASSWORD__"

    [apim.analytics]
    enable = false
