apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2apim-pvc
  namespace: apim-wso2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
