apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s
  namespace: monitoring
  labels:
    app: prometheus-k8s
spec:
  type: ClusterIP
  selector:
    prometheus: prometheus-k8s
  ports:
    - name: web
      port: 9090
      targetPort: web
