apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s-nodeport
  namespace: monitoring
  labels:
    app: prometheus-k8s
spec:
  type: NodePort
  selector:
    prometheus: prometheus-k8s
  ports:
    - name: web
      port: 9090
      targetPort: web
      nodePort: 30091
