apiVersion: v1
kind: ConfigMap
metadata:
  name: gravitee-management-config
  namespace: apim-gravitee
data:
  gravitee.yml.tpl: |
    management:
      type: mongodb
      mongodb:
        uri: mongodb://gravitee:__MONGO_PASSWORD__@gravitee-mongo.apim-gravitee.svc.cluster.local:27017/gravitee?authSource=admin

    analytics:
      type: elasticsearch
      elasticsearch:
        endpoints:
          - http://gravitee-elasticsearch.apim-gravitee.svc.cluster.local:9200

    jwt:
      secret: "gravitee-poc-jwt-secret-2026"

    security:
      providers:
        - type: memory
          password-encoding-algo: bcrypt
          users:
            - user:
                username: admin
                password: $2a$10$Ihk05VSds5rUSgMdsMVi9OKMIx2yUvMz7y9VP3rJmQeizZLrhLMyq
                roles: ORGANIZATION:ADMIN,ENVIRONMENT:ADMIN

    http:
      api:
        management:
          entrypoint: "/management"
          proxyPath: "/management"
      secureHeaders:
        referrerPolicy:
          policy: no-referrer

    installation:
      api:
        url: https://apim-gravitee.local:31443
        proxyPath:
          management: "/management"
          portal: "/portal"
      standalone:
        console:
          url: https://apim-gravitee.local:31443
        portal:
          url: https://portal-gravitee.local:31443

    portal:
      url: https://portal-gravitee.local
