apiVersion: v1
kind: Secret
metadata:
  name: wso2-keystore
  namespace: apim-wso2
stringData:
  # Estos archivos se inyectan desde Vault Agent (sidecar) en runtime.
  # Aquí solo dejamos los nombres para referencia.
  keystore.p12: "__INJECTED_BY_VAULT__"
  truststore.p12: "__INJECTED_BY_VAULT__"
